### ISSUE TITLE
Feature Request: Geometric Specular Anti-aliasing

### ISSUE THREAD

**Issue by cubedparadox** [Xiexe/XSEnvironmentShaders#1]
Help, I've upgraded from the deprecated PBR_Standard_Dithered_GSAA_SLO shader and this new environment shader is missing an important feature, geometric specular anti-aliasing!

**Comment by Xiexe** [comment]
Will be added in a future version.

**Comment by owlboy** [comment]
🙏

**Comment by owlboy** [comment]
Shouldn't this at least be marked "Under Review" now?

**Comment by Xiexe** [comment]
No, it should be closed because it was added and I forgot about the issue :p
