### ISSUE TITLE
Occlusion Map

### ISSUE THREAD

**Issue by owlboy** [Xiexe/XSEnvironmentShaders#5]
The occlusion map does not work as expected. A 100% black map does not make the model 100% black as it does with Standard.

**Comment by owlboy** [comment]
I may have found it works in Triplanar mode.

**Comment by owlboy** [comment]
Not sure that was true. I do find it applies quite dramatically in some situations, and in others, I can barely get it to register unless I over crank it. And at that point, it has strong artifacts/contrast.

Is this a side effect of it seeming to be designed to be inverted to brighten materials in addition to the normal multiply Occlusion has? Is this is a different sort of mix other than Multiply?

**Comment by Xiexe** [comment]
Fixed in latest merge to master branch!
